name: Upload Terraform State to S3

on:
  push:
    branches:
      - main

jobs:
  upload-state:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
     
      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="deploy.tfvars"
      - name: Debug â€” List workspace structure
        run: |
          echo "Current Directory:"
          pwd
          echo "------ FILE STRUCTURE ------"
          ls -R .
      - name: Upload terraform.tfstate to S3
        run: |
          echo "Looking for tfstate file..."
          find . -name "*.tfstate"

          echo "Uploading terraform.tfstate to S3..."
          aws s3 cp .terraform/terraform.tfstate s3://exemplifi-test-ap-northeast-1/states/terraform.tfstate --acl private
