name: Terraform CI Pipeline

on:
  push:                           # CREATE infra on push to main
    branches:
      - main

  workflow_dispatch:              # DESTROY infra manually
    inputs:
      action:
        description: "Choose Action: apply or destroy"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

jobs:

  terraform-apply:
    if: github.event_name == 'push' || github.event.inputs.action == 'apply'
    name: Terraform Apply Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="deploy.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="deploy.tfvars"

      - name: Get EC2 Public IP
        id: tf_output
        run: |
         EC2_IP=$(terraform output -raw ec2_public_ip)
         echo "ec2_ip=$EC2_IP" >> $GITHUB_OUTPUT

      - name: Save EC2 Public IP to GitHub Secret
        env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         EC2_IP: ${{ steps.tf_output.outputs.ec2_ip }}
        run: |
         gh secret set EC2_PUBLIC_IP --body "$EC2_IP"


  terraform-destroy:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
    name: Terraform Destroy Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file="deploy.tfvars"
